version: '3.8'

services:
  media-video-dump:
    build: .
    # image: media_video_dump_service.slim:latest
    # image: media-video-dump-media-video-dump.slim
    ports:
      - "8000:8000"
    volumes:
      - ./media_video_dump/downloads:/app/media_video_dump/downloads
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
